# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 040d7d21ba7f36dd045a5299c645b1549bbcf11e72c5599e344edf406a0505445e270f8017680e6a24c61fe7497637429d880d87407861e00ec4fc2e372ada33

test:
  secret_key_base: 16b9ceaa57b969c6e46768c33a69b9493bea8d82b3172ca97f613d6431961298aee5e93d7b19be63dd8ba9ebca3809da61bc89016986731f5c255a5faa2b3a2f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
